import { useState } from "react";
import { Download, FileText, Plus, Trash2 } from "lucide-react";

interface Step {
  id: number;
  description: string;
}

interface FormData {
  title: string;
  author: string;
  date: string;
  hypothesis: string;
  tools: string;
  environment: string;
  steps: Step[];
  results: string;
  conclusion: string;
  dataLocation: string;
}

export default function DocumentationTemplate() {
  const [form, setForm] = useState<FormData>({
    title: "",
    author: "",
    date: new Date().toISOString().split("T")[0],
    hypothesis: "",
    tools: "",
    environment: "",
    steps: [{ id: 1, description: "" }],
    results: "",
    conclusion: "",
    dataLocation: "",
  });

  const addStep = () => {
    setForm((f) => ({
      ...f,
      steps: [...f.steps, { id: f.steps.length + 1, description: "" }],
    }));
  };

  const removeStep = (id: number) => {
    setForm((f) => ({ ...f, steps: f.steps.filter((s) => s.id !== id) }));
  };

  const updateStep = (id: number, val: string) => {
    setForm((f) => ({
      ...f,
      steps: f.steps.map((s) => (s.id === id ? { ...s, description: val } : s)),
    }));
  };

  const handleDownload = () => {
    const content = `
EXPERIMENT DOCUMENTATION REPORT
================================
Generated by ReproLab NG — ${new Date().toLocaleDateString()}

EXPERIMENT TITLE: ${form.title || "—"}
AUTHOR(S): ${form.author || "—"}
DATE: ${form.date || "—"}

HYPOTHESIS
----------
${form.hypothesis || "—"}

TOOLS & DEPENDENCIES
--------------------
${form.tools || "—"}

ENVIRONMENT SETUP
-----------------
${form.environment || "—"}

EXPERIMENTAL STEPS
------------------
${form.steps.map((s, i) => `${i + 1}. ${s.description || "—"}`).join("\n")}

RESULTS & OBSERVATIONS
----------------------
${form.results || "—"}

CONCLUSION
----------
${form.conclusion || "—"}

DATA LOCATION / REPOSITORY
---------------------------
${form.dataLocation || "—"}

---
This document was generated using ReproLab NG to promote reproducibility
in software engineering research across Nigeria.
`.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `experiment-${form.title.replace(/\s+/g, "-").toLowerCase() || "report"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const inputClass =
    "w-full px-4 py-3 text-sm rounded-xl border border-border bg-background focus:outline-none focus:ring-2 focus:ring-green/40 focus:border-green transition-all placeholder:text-muted-foreground";
  const labelClass = "block text-sm font-semibold text-foreground mb-1.5";

  return (
    <section id="documentation" className="py-24" style={{ background: "var(--gradient-subtle)" }}>
      <div className="container max-w-4xl mx-auto px-4">
        {/* Heading */}
        <div className="text-center mb-14">
          <span className="inline-block px-3 py-1 text-xs font-semibold text-green-dark bg-green-muted rounded-full mb-4 uppercase tracking-wider">
            Step 2
          </span>
          <h2 className="section-heading text-4xl md:text-5xl font-bold text-navy mb-4">
            Experiment Documentation
          </h2>
          <p className="text-muted-foreground max-w-2xl mx-auto text-lg">
            Fill out this standardized template to document your experiment thoroughly, then download it for your records.
          </p>
        </div>

        {/* Form */}
        <div className="bg-card rounded-2xl border border-border p-8 shadow-card space-y-8">
          {/* Basic Info */}
          <div>
            <div className="flex items-center gap-2 mb-5">
              <div className="w-7 h-7 rounded-lg flex items-center justify-center text-xs font-bold text-white" style={{ background: "var(--gradient-accent)" }}>1</div>
              <h3 className="font-heading font-semibold text-lg text-navy">Basic Information</h3>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              <div>
                <label className={labelClass}>Experiment Title *</label>
                <input className={inputClass} placeholder="e.g., Comparing Sort Algorithm Performance" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} />
              </div>
              <div>
                <label className={labelClass}>Author(s) *</label>
                <input className={inputClass} placeholder="e.g., Chidi Okeke, Amina Bello" value={form.author} onChange={(e) => setForm({ ...form, author: e.target.value })} />
              </div>
              <div className="md:col-span-2">
                <label className={labelClass}>Date</label>
                <input type="date" className={inputClass} value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} />
              </div>
            </div>
          </div>

          <div className="section-divider" />

          {/* Hypothesis */}
          <div>
            <div className="flex items-center gap-2 mb-5">
              <div className="w-7 h-7 rounded-lg flex items-center justify-center text-xs font-bold text-white" style={{ background: "var(--gradient-accent)" }}>2</div>
              <h3 className="font-heading font-semibold text-lg text-navy">Hypothesis & Objective</h3>
            </div>
            <textarea className={`${inputClass} resize-none`} rows={3} placeholder="State your research question or hypothesis clearly..." value={form.hypothesis} onChange={(e) => setForm({ ...form, hypothesis: e.target.value })} />
          </div>

          <div className="section-divider" />

          {/* Tools & Environment */}
          <div>
            <div className="flex items-center gap-2 mb-5">
              <div className="w-7 h-7 rounded-lg flex items-center justify-center text-xs font-bold text-white" style={{ background: "var(--gradient-accent)" }}>3</div>
              <h3 className="font-heading font-semibold text-lg text-navy">Tools & Environment</h3>
            </div>
            <div className="space-y-4">
              <div>
                <label className={labelClass}>Tools & Libraries Used</label>
                <textarea className={`${inputClass} resize-none`} rows={2} placeholder="e.g., Python 3.11, NumPy 1.24, Pandas 2.0, scikit-learn 1.3" value={form.tools} onChange={(e) => setForm({ ...form, tools: e.target.value })} />
              </div>
              <div>
                <label className={labelClass}>Environment Configuration</label>
                <textarea className={`${inputClass} resize-none`} rows={2} placeholder="e.g., Ubuntu 22.04, 16GB RAM, conda env exported as environment.yml" value={form.environment} onChange={(e) => setForm({ ...form, environment: e.target.value })} />
              </div>
            </div>
          </div>

          <div className="section-divider" />

          {/* Steps */}
          <div>
            <div className="flex items-center gap-2 mb-5">
              <div className="w-7 h-7 rounded-lg flex items-center justify-center text-xs font-bold text-white" style={{ background: "var(--gradient-accent)" }}>4</div>
              <h3 className="font-heading font-semibold text-lg text-navy">Experimental Steps</h3>
            </div>
            <div className="space-y-3">
              {form.steps.map((step, index) => (
                <div key={step.id} className="flex gap-3 items-start">
                  <span className="mt-3 w-6 h-6 flex-shrink-0 rounded-full bg-green-muted text-green-dark text-xs font-bold flex items-center justify-center">
                    {index + 1}
                  </span>
                  <input
                    className={inputClass}
                    placeholder={`Step ${index + 1}: Describe what you did...`}
                    value={step.description}
                    onChange={(e) => updateStep(step.id, e.target.value)}
                  />
                  {form.steps.length > 1 && (
                    <button onClick={() => removeStep(step.id)} className="mt-3 text-muted-foreground hover:text-destructive transition-colors">
                      <Trash2 className="w-4 h-4" />
                    </button>
                  )}
                </div>
              ))}
              <button onClick={addStep} className="flex items-center gap-2 text-sm font-medium text-green-dark hover:text-green transition-colors mt-2">
                <Plus className="w-4 h-4" /> Add Step
              </button>
            </div>
          </div>

          <div className="section-divider" />

          {/* Results & Conclusion */}
          <div>
            <div className="flex items-center gap-2 mb-5">
              <div className="w-7 h-7 rounded-lg flex items-center justify-center text-xs font-bold text-white" style={{ background: "var(--gradient-accent)" }}>5</div>
              <h3 className="font-heading font-semibold text-lg text-navy">Results & Conclusion</h3>
            </div>
            <div className="space-y-4">
              <div>
                <label className={labelClass}>Results & Observations</label>
                <textarea className={`${inputClass} resize-none`} rows={3} placeholder="Describe what you observed, metrics collected, data gathered..." value={form.results} onChange={(e) => setForm({ ...form, results: e.target.value })} />
              </div>
              <div>
                <label className={labelClass}>Conclusion</label>
                <textarea className={`${inputClass} resize-none`} rows={2} placeholder="Summarize your findings and whether your hypothesis was supported..." value={form.conclusion} onChange={(e) => setForm({ ...form, conclusion: e.target.value })} />
              </div>
              <div>
                <label className={labelClass}>Data Location / Repository URL</label>
                <input className={inputClass} placeholder="e.g., https://github.com/your-repo or Google Drive link" value={form.dataLocation} onChange={(e) => setForm({ ...form, dataLocation: e.target.value })} />
              </div>
            </div>
          </div>

          {/* Download Button */}
          <div className="pt-2">
            <button
              onClick={handleDownload}
              className="w-full flex items-center justify-center gap-2 py-4 rounded-xl text-base font-semibold text-white transition-all btn-primary"
              style={{ background: "var(--gradient-accent)" }}
            >
              <Download className="w-5 h-5" />
              Download Documentation Report
            </button>
            <p className="text-center text-xs text-muted-foreground mt-3">
              Downloads as a plain text file. Share with collaborators for reproducibility.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
